C:\Users\User\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\User\\Desktop\\p2p-udp\\work\\example.zip\\main.py': [Errno 2] No such file or directory
